### Lines starting with "#$" are options for the SGE scheduling system
#$ -S /bin/bash    # Set shell to run job
#$ -q all.q        # Choose queue to run job in
#$ -pe orte 1      # Request one processor from parallel env.
#$ -cwd            # Run job from my current working directory

export AMBERHOME="/home/mc26/amber18"
export PATH="${AMBERHOME}/bin:$PATH"

##Commands go below
pmemd -O -i minimize.in -o minimize.out -p protein_helix_nohydrogen.prmtop -c protein_helix_nohydrogen.inpcrd -r minimize.rst -x minimize.mdcrd -inf minimize.mdinfo -ref protein_helix_nohydrogen.inpcrd
