### Lines starting with "#$" are options for the SGE scheduling system
#$ -S /bin/bash    # Set shell to run job
#$ -q all.q        # Choose queue to run job in
#$ -pe orte 16      # Request one processor from parallel env.
#$ -cwd            # Run job from my current working directory

export LD_LIBRARY_PATH=/opt/gridengine/lib/linux-x64:/opt/openmpi/lib:/opt/python/lib

export AMBERHOME="/home/mc26/amber18"
export PATH="${AMBERHOME}/bin:$PATH"

##Commands go below
#
mpirun -np 16 pmemd.MPI
